version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: databasename
    volumes:
      - postgres_data:/var/lib/postgresql/data # Named volume for Postgree
    ports:
      - 5432:5432
    networks:
      - my_network

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    volumes:
      - django_static:/app/Yourproject/static  # Named volume for Django static files
    ports:
      - 8000:8000 # i run on port 8000
    networks:
      - my_network
    command: sh -c "chmod +x .env/Scripts/Activate.ps1 && git pull origin main && python manage.py makemigrations && python manage.py migrate && gunicorn Yourproject.wsgi:application -b 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - django_static:/app/Yourproject/static  # Use the same named volume for Nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
    networks:
      - my_network

volumes:
  postgres_data:  # Named volume for Postgree
  django_static:  # Named volume for Django static files
